version: '2'
services:
    thepellestore-app:
        image: thepellestore
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://thepellestore-mysql:3306/thepellestore?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES=thepellestore-elasticsearch:9300
        ports:
            - 8080:8080
    thepellestore-mysql:
        extends:
            file: mysql.yml
            service: thepellestore-mysql
    thepellestore-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: thepellestore-elasticsearch
